on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_proxmox_password: ${{ secrets.PROXMOX_TF_PASSWORD }}
  TF_VAR_container_root_password: "${{ secrets.CONTAINER_ROOT_PASSWORD }}"
  TF_VAR_container_name: "${{ vars.CONTAINER_NAME }}"
  TF_VAR_container_ip: "${{ vars.CONTAINER_IP }}"

jobs:
  terraform:
    name: "Provision infrastructure (container)"
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
          terraform_wrapper: false

      - name: TF Init
        working-directory: ./terraform
        run: terraform init

      - name: TF Plan
        working-directory: ./terraform
        run: terraform plan -input=false

      - name: TF Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false

      - name: Get container IP from Terraform
        id: get_ip
        working-directory: ./terraform
        run: |
          CONTAINER_IP=$(terraform output -raw container_ip)
          echo "container_ip=$CONTAINER_IP" >> $GITHUB_OUTPUT
          echo "Container IP: $CONTAINER_IP"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CONTAINER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Generate Ansible inventory
        working-directory: ./ansible
        run: |
          echo "nginx ansible_host=${{ steps.get_ip.outputs.container_ip }} ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=no'" > inventory

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: |
          python3 -m ansible.cli.playbook playbook.yml -i inventory.yml
